<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AulasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AulasRepository extends EntityRepository {
    public function getAulas() {
         return $this->getEntityManager()
            ->createQuery('SELECT a FROM CriveroPruebaBundle:Aulas a')
            ->getResult();
    }
    public function getNombreAulas(){
        return $this->getEntityManager()
            ->createQuery('SELECT a.nombre FROM CriveroPruebaBundle:Aulas a')
            ->getResult();
    }
}
