<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CanchasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanchasRepository extends EntityRepository {
    
    public function getCanchas() {
         return $this->getEntityManager()
            ->createQuery('SELECT c FROM CriveroPruebaBundle:Canchas c')
            ->getResult();
    }
    
    public function searchCanchas($searchQuery) {
        return $this->getEntityManager()
            ->createQuery("SELECT c FROM CriveroPruebaBundle:Canchas c WHERE c.tipo= :nombre")
            ->setParameter('nombre', $searchQuery)
            ->getResult();
    }
}
