<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComentariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentariosRepository extends EntityRepository {

    public function getMensajesRecibidos($usuarioId) {
        return $this->getEntityManager()
                        ->createQueryBuilder()->select('m')
                        ->from('CriveroPruebaBundle:Comentarios', 'm')
                        ->where("m.idDestinatario = :dest")
                        ->setParameter('dest', $usuarioId)
                        ->orderBy("m.fecha", 'DESC')
                        ->getQuery();
    }
    
    public function getMensajesRecibidosNoOrden($usuarioId) {
        return $this->getEntityManager()
                        ->createQueryBuilder()->select('m')
                        ->from('CriveroPruebaBundle:Comentarios', 'm')
                        ->where("m.idDestinatario = :dest")
                        ->setParameter('dest', $usuarioId)
                        ->getQuery()->getResult();
    }

    public function getMensajesEnviados($usuarioId) {
        return $this->getEntityManager()
                        ->createQueryBuilder()->select('m')
                        ->from('CriveroPruebaBundle:Comentarios', 'm')
                        ->where("m.idRemitente = :rmt")
                        ->setParameter('rmt', $usuarioId)
                        ->orderBy("m.fecha", 'DESC')
                        ->getQuery();
    }

}
