<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComentariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentariosRepository extends EntityRepository {
     public function getMensajesRecibidos($usuarioId) {
        return $this->getEntityManager()
                        ->createQuery('SELECT m FROM CriveroPruebaBundle:Comentarios m WHERE m.idDestinatario = :dest')
                        ->setParameter('dest', $usuarioId)
                        ->getResult();
    }
    
     public function getMensajesEnviados($usuarioId) {
        return $this->getEntityManager()
                        ->createQuery('SELECT m FROM CriveroPruebaBundle:Comentarios m WHERE m.idRemitente = :rmt')
                        ->setParameter('rmt', $usuarioId)
                        ->getResult();
    }
}
