<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompeticionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompeticionesRepository extends EntityRepository {

    public function getCompeticionesValidadas() {
        return $this->getEntityManager()
                        ->createQuery("SELECT c FROM CriveroPruebaBundle:Competiciones c WHERE c.estadocompeticion='Validado'")
                        ->getResult();
    }

}
