<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquiposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquiposRepository extends EntityRepository
{
    public function findAllMisEquipos($idCliente)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT equipos FROM CriveroPruebaBundle:Equipos equipos
                           WHERE  equipos.idCliente = :idCliente')
            ->setParameter('idCliente', $idCliente)
            ->getResult();
    }
    public function getEquiposCompeticion($idCompeticion){
        return $this->getEntityManager()
            ->createQuery('SELECT equipos FROM CriveroPruebaBundle:Equipos equipos
                           WHERE  equipos.idCompeticion = :idCompeticion 
                           ORDER BY equipos.clasificacion ASC ')
            ->setParameter('idCompeticion', $idCompeticion)
            ->getResult();
    }
}