<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquiposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquiposRepository extends EntityRepository
{
    public function findAllMisEquipos($idCliente)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT equipos FROM CriveroPruebaBundle:Equipos equipos
                           WHERE  equipos.idCliente = :idCliente')
            ->setParameter('idCliente', $idCliente)
            ->getResult();
    }
    
    public function findEquipoJugador($idEquipoJugador)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT equipos FROM CriveroPruebaBundle:Equipos equipos
                           WHERE  equipos.id = :idEquipoJugador')
            ->setParameter('idEquipoJugador', $idEquipoJugador)
            ->getResult();
    }
    public function getEquiposCompeticion($idCompeticion){
        return $this->getEntityManager()
            ->createQuery('SELECT equipos FROM CriveroPruebaBundle:Equipos equipos
                           WHERE  equipos.idCompeticion = :idCompeticion 
                           ORDER BY equipos.clasificacion ASC ')
            ->setParameter('idCompeticion', $idCompeticion)
            ->getResult();
    }
    
    public function searchEquipos($searchQuery) {
        return $this->getEntityManager()
            ->createQuery("SELECT equipos FROM CriveroPruebaBundle:Equipos equipos"
                    . " WHERE equipos.nombre= :nombre"
                    . " OR equipos.deporte = :deporte")
            ->setParameter('nombre', $searchQuery)
            ->setParameter('deporte', $searchQuery)
            ->getResult();
    }
    
    public function searchEquiposCliente($searchQuery,$idCliente) {
        return $this->getEntityManager()
            ->createQuery("SELECT equipos FROM CriveroPruebaBundle:Equipos equipos"
                    . " WHERE equipos.idCliente = :idCliente AND"
                    . " (equipos.nombre = :nombre OR equipos.deporte = :deporte)")
            ->setParameter('idCliente', $idCliente)
            ->setParameter('nombre', $searchQuery)
            ->setParameter('deporte', $searchQuery)
            ->getResult();
    }
}