<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HorariosCanchasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorariosCanchasRepository extends EntityRepository {
    public function getHorario($cancha, $dia) {
    return $this->getEntityManager()
                        ->createQuery('SELECT h.periodo FROM CriveroPruebaBundle:HorariosCanchas h WHERE h.cancha = :canchaId')
                        ->setParameter('canchaId', $cancha)
                        ->getResult();
    }
}
