<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionesRepository extends EntityRepository {

    public function getNotificaciones($id) {
        return $this->getEntityManager()
                        ->createQuery("SELECT n FROM CriveroPruebaBundle:Notificaciones n WHERE n.idDestinatario = :id")
                        ->setParameter('id', $id)
                        ->getResult();
    }

    public function getNotificacionEntidad($id, $idUsuario) {
        return $this->getEntityManager()
                        ->createQuery("SELECT n FROM CriveroPruebaBundle:Notificaciones n WHERE n.idEntidad = :id AND n.idDestinatario = :idUsuario")
                        ->setParameter('id', $id)
                        ->setParameter('idUsuario', $idUsuario)
                        ->getResult();
    }

}
