<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PagosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagosRepository extends EntityRepository {
     public function getPagos($id){
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM CriveroPruebaBundle:Pagos p WHERE p.idCliente = :id')
            ->setParameter('id', $id)    
            ->getResult();
    }
}
