<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservasRepository extends EntityRepository {

    public function getReservas() {
        return $this->getEntityManager()
                        ->createQueryBuilder()->select('r')
                        ->from('CriveroPruebaBundle:Reservas', 'r')
                        ->where("r.estadoReserva='Reservado'")
                        ->getQuery();
    }

    public function getReservasCliente($id) {
        return $this->getEntityManager()
                        ->createQueryBuilder()->select('r')
                        ->from('CriveroPruebaBundle:Reservas', 'r')
                        ->where("r.idCliente = :id")
                        ->setParameter('id', $id)
                        ->getQuery();
    }

    public function searchReservas($searchQuery) {
        return $this->getEntityManager()
                        ->createQuery("SELECT r FROM CriveroPruebaBundle:Reservas r WHERE r.estadoReserva = 'Reservado'"
                                    . "AND (r.cliente LIKE '%{$searchQuery}%' OR r.cancha LIKE '%{$searchQuery}%') ");
    }

    public function searchReservasCliente($searchQuery, $id) {
        return $this->getEntityManager()
        ->createQuery("SELECT r FROM CriveroPruebaBundle:Reservas r WHERE r.estadoReserva = 'Reservado' AND r.idCliente = :id AND r.cancha LIKE '%{$searchQuery}%'")
                ->setParameter('id', $id)
                ->getResult();
    }
    
    public function getReservasCancha($id) {
        return $this->getEntityManager()
                        ->createQueryBuilder()->select('r')
                        ->from('CriveroPruebaBundle:Reservas', 'r')
                        ->where("r.estadoReserva = 'Reservado'")
                        ->andWhere("r.idCancha = :id")
                        ->setParameter('id', $id)
                        ->getQuery();
    }
    
    public function getAllReservasCancha($id) {
        return $this->getEntityManager()
                    ->createQueryBuilder()->select('r')
                    ->from('CriveroPruebaBundle:Reservas', 'r')
                    ->where("r.idCancha = :id")
                    ->setParameter('id', $id)
                    ->getQuery();
    }


}
