<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservasRepository extends EntityRepository {

    public function getReservas() {
        return $this->getEntityManager()
                        ->createQueryBuilder()->select('r')
                        ->from('CriveroPruebaBundle:Reservas', 'r')
                        ->where("r.estadoReserva='Reservado'")
                        ->getQuery();
    }

    public function getReservasCliente($id) {
        return $this->getEntityManager()
                        ->createQueryBuilder()->select('r')
                        ->from('CriveroPruebaBundle:Reservas', 'r')
                        ->where("r.estadoReserva = 'Reservado'")
                        ->andWhere("r.idCliente = :id")
                        ->setParameter('id', $id)
                        ->getQuery();
    }

    public function searchReservas($searchQuery) {
        return $this->getEntityManager()
                        ->createQueryBuilder()->select('r')
                        ->from('CriveroPruebaBundle:Reservas', 'r')
                        ->where("r.estadoReserva = 'Reservado'")
                        ->andWhere("r.cliente = :cliente")
                        ->orWhere("r.cancha = :cancha")
                        ->setParameter('cliente', $searchQuery)
                        ->setParameter('cancha', $searchQuery)
                        ->getQuery();
    }

    public function searchReservasCliente($searchQuery, $id) {
        return $this->getEntityManager()
        ->createQuery("SELECT r FROM CriveroPruebaBundle:Reservas r WHERE r.estadoReserva = 'Reservado' AND r.idCliente = :id AND r.cancha = :cancha ")
                ->setParameter('id', $id)
                ->setParameter('cancha', $searchQuery)
                ->getResult();
    }

}
