<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SesionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SesionesRepository extends EntityRepository {
    
    public function getSesionesGenerales() {
         return $this->getEntityManager()
            ->createQuery("SELECT s FROM CriveroPruebaBundle:Sesiones s WHERE s.cliente='normal'")
            ->getResult();
    }
    
    public function getSesionesDedicadas() {
         return $this->getEntityManager()
            ->createQuery("SELECT s FROM CriveroPruebaBundle:Sesiones s WHERE s.cliente!='normal'")
            ->getResult();
    }
}
