<?php

namespace Crivero\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValoracionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoracionesRepository extends EntityRepository {

    public function getIdCanchas($id) {
        return $this->getEntityManager()
                        ->createQuery('SELECT v FROM CriveroPruebaBundle:Valoraciones v WHERE v.idCancha=:id')
                        ->setParameter('id', $id)
                        ->getResult();
    }

    public function findCliente($id) {
        return $this->getEntityManager()
                        ->createQuery('SELECT u FROM CriveroPruebaBundle:Valoraciones u WHERE u.idCliente=:id')
                        ->setParameter('id', $id)
                        ->getResult();
    }

}
