security:

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_db_provider:
            entity:
                class: CriveroPruebaBundle:Usuarios
                property: nombre

    firewalls:
        default:
                anonymous: ~
                http_basic: ~
                form_login:
                    login_path: /login
                    check_path: /login_check
                    # field names for the username and password fields:
                    username_parameter: _nombre
                    password_parameter: _password
                    # default_target_path: default_security_target
                    # always_use_default_target_path: true
                logout:
                    path:   /logout
                    target: /login
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    
    encoders:
        Crivero\PruebaBundle\Entity\Usuarios:
            algorithm: bcrypt
            cost: 12