modulomonitores_monitores_homeMonitores:
    pattern:  /homeMonitores
    defaults: { _controller: modulomonitoresmonitoresBundle:Home:homeMonitores }
    
modulomonitores_monitores_sesionesMonitores:
    pattern:  /sesionesMonitores
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:sesionesMonitores }
    
modulomonitores_monitores_sesionMonitores:
    pattern:  /sesionMonitores/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:sesionMonitores }    

modulomonitores_monitores_sesionesDedicadas:
    pattern:  /sesionesDedicadas
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:sesionesDedicadas }    
    
modulomonitores_monitores_sesionDedicada:
    pattern:  /sesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:sesionDedicada } 
modulomonitores_monitores_misSesionesMonitores:
    pattern:  /misSesionesMonitores
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:misSesionesMonitores }
    
modulomonitores_monitores_miSesionMonitores:
    pattern:  /miSesionMonitores/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:miSesionMonitores }    

modulomonitores_monitores_misSesionesDedicadas:
    pattern:  /misSesionesDedicadas
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:misSesionesDedicadas }    
    
modulomonitores_monitores_miSesionDedicada:
    pattern:  /miSesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:miSesionDedicada } 
    
modulomonitores_monitores_nuevaSesion:
    pattern:  /nuevaSesion
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:nuevaSesion }
modulomonitores_monitores_editarSesion:
    pattern:  /editarSesion/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:editarSesion }
modulomonitores_monitores_editarSesionDedicada:
    pattern:  /editarSesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:editarSesionDedicada }
modulomonitores_monitores_solEliminarSesion:
    pattern:  /solEliminarSesion/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:solEliminarSesion }    
modulomonitores_monitores_solElimSe:
    pattern:  /solElimSe/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:solElimSe }
    requirements:
        _method:  POST|PUT|GET  
modulomonitores_monitores_solEliminarSesionDedicada:
    pattern:  /solEliminarSesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:solEliminarSesionDedicada }    
modulomonitores_monitores_solElimSeDe:
    pattern:  /solElimSeDe/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:solElimSeDe }
    requirements:
        _method:  POST|PUT|GET  
modulomonitores_monitores_nuevaSesionDedicada:
    pattern:  /nuevaSesionDedicada
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:nuevaSesionDedicada }
modulomonitores_monitores_crearSesion:
    pattern:  /crearSesion
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:crearSesion }
    requirements:
        _method:  POST|GET
modulomonitores_monitores_editar:
    pattern:  /editar/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:editar }
    requirements:
        _method:  POST|PUT|GET
modulomonitores_monitores_editarDedicada:
    pattern:  /editarDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:editarDedicada }
    requirements:
        _method:  POST|PUT|GET
modulomonitores_monitores_crearSesionDedicada:
    pattern:  /crearSesionDedicada
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:crearSesionDedicada }
    requirements:
        _method:  POST|GET
modulomonitores_monitores_eliminarSesion:
    pattern:  /eliminarSesion/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:eliminarSesion}
    methods: [POST, DELETE]
modulomonitores_monitores_eliminarSesionDedicada:
    pattern:  /eliminarSesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:eliminarSesionDedicada}
    methods: [POST, DELETE]