modulomonitores_monitores_homeMonitores:
    pattern:  /homeMonitores
    defaults: { _controller: modulomonitoresmonitoresBundle:Home:homeMonitores }
    
modulomonitores_monitores_sesionesMonitores:
    pattern:  /sesionesMonitores
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:sesionesMonitores }
    
modulomonitores_monitores_sesionMonitores:
    pattern:  /sesionMonitores/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:sesionMonitores }    

modulomonitores_monitores_sesionesDedicadas:
    pattern:  /sesionesDedicadas
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:sesionesDedicadas }    
    
modulomonitores_monitores_sesionDedicada:
    pattern:  /sesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:sesionDedicada } 
    
modulomonitores_monitores_nuevaSesion:
    pattern:  /nuevaSesion
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:nuevaSesion }
modulomonitores_monitores_nuevaSesionDedicada:
    pattern:  /nuevaSesionDedicada
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:nuevaSesionDedicada }
modulomonitores_monitores_crearSesion:
    pattern:  /crearSesion
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:crearSesion }
    requirements:
        _method:  POST|GET
modulomonitores_monitores_crearSesionDedicada:
    pattern:  /crearSesionDedicada
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:crearSesionDedicada }
    requirements:
        _method:  POST|GET
