modulomonitores_monitores_homeMonitores:
    pattern:  /homeMonitores
    defaults: { _controller: modulomonitoresmonitoresBundle:Home:homeMonitores }
    
modulomonitores_monitores_sesionesMonitores:
    pattern:  /sesionesMonitores
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:sesionesMonitores }
    
modulomonitores_monitores_sesionMonitores:
    pattern:  /sesionMonitores/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:sesionMonitores }    

modulomonitores_monitores_sesionesDedicadas:
    pattern:  /sesionesDedicadas
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:sesionesDedicadas }    
    
modulomonitores_monitores_sesionDedicada:
    pattern:  /sesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:sesionDedicada } 
modulomonitores_monitores_misSesionesMonitores:
    pattern:  /misSesionesMonitores
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:misSesionesMonitores }
    
modulomonitores_monitores_miSesionMonitores:
    pattern:  /miSesionMonitores/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:miSesionMonitores }    

modulomonitores_monitores_misSesionesDedicadas:
    pattern:  /misSesionesDedicadas
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:misSesionesDedicadas }    
    
modulomonitores_monitores_miSesionDedicada:
    pattern:  /miSesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:miSesionDedicada } 
    
modulomonitores_monitores_nuevaSesion:
    pattern:  /nuevaSesion
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:nuevaSesion }
modulomonitores_monitores_editarSesion:
    pattern:  /editarSesion/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:editarSesion }
modulomonitores_monitores_editarSesionDedicada:
    pattern:  /editarSesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:editarSesionDedicada }
modulomonitores_monitores_suspender:
    pattern:  /suspender/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:suspender }    
modulomonitores_monitores_suspenderSe:
    pattern:  /suspenderSe/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:suspenderSe }
    requirements:
        _method:  POST|PUT|GET  
modulomonitores_monitores_suspenderSesionDedicada:
    pattern:  /suspenderSesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:suspenderSesionDedicada }    
modulomonitores_monitores_suspenderSeDe:
    pattern:  /suspenderSeDe/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:suspenderSeDe }
    requirements:
        _method:  POST|PUT|GET  
modulomonitores_monitores_nuevaSesionDedicada:
    pattern:  /nuevaSesionDedicada
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:nuevaSesionDedicada }
modulomonitores_monitores_crearSesion:
    pattern:  /crearSesion
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:crearSesion }
    requirements:
        _method:  POST|GET
modulomonitores_monitores_editar:
    pattern:  /editar/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:editar }
    requirements:
        _method:  POST|PUT|GET
modulomonitores_monitores_editarDedicada:
    pattern:  /editarDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:editarDedicada }
    requirements:
        _method:  POST|PUT|GET
modulomonitores_monitores_crearSesionDedicada:
    pattern:  /crearSesionDedicada
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:crearSesionDedicada }
    requirements:
        _method:  POST|GET
modulomonitores_monitores_eliminarSesion:
    pattern:  /eliminarSesion/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:eliminarSesion}
    methods: [POST, DELETE]
modulomonitores_monitores_eliminarSesionDedicada:
    pattern:  /eliminarSesionDedicada/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Dedicada:eliminarSesionDedicada}
    methods: [POST, DELETE]
modulomonitores_monitores_miperfilm:
    pattern:  /monitor/perfil
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:miperfilm}
    
modulomonitores_monitores_editarmiperfilm:
    pattern:  /editarmiperfilm
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:editarmiperfilm }

modulomonitores_monitores_actualizarmiperfilm:
    pattern:  /actualizarmiperfilm
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:actualizarmiperfilm }
    
modulomonitores_monitores_verParticipantes:
    pattern:  /miSesionMonitores/{id}/verParticipantes
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:verParticipantes }
modulomonitores_monitores_participante:
    pattern:  /miSesionMonitores/{id}/verParticipantes/{idUsuario}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:participante }
modulomonitores_monitores_participantePrivado:
    pattern:  /miSesionMonitores/{id}/participantePrivado
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:participantePrivado }
modulomonitores_monitores_abandonarSesion:
    pattern:  /abandonarSesion/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:abandonarSesion}
modulomonitores_monitores_expulsar:
    pattern:  /expulsar/{id}/{idUsuario}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:expulsar}
modulomonitores_monitores_verHorario:
    pattern:  /verHorario/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:verHorario }    
    
modulomonitores_monitores_terminar:
    pattern:  /terminar/{id}
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:terminar }
    requirements:
        _method:  POST|PUT|GET

modulomonitores_monitores_notificacionesMonitor:
    pattern:  /notificacionesMonitor
    defaults: { _controller: modulomonitoresmonitoresBundle:Sesion:notificacionesMonitor }